-- Migration 003: Update camera_id to auto-increment bigint
-- Run timestamp: 2025-08-21

-- Add new bigint camera_id_new column with auto-increment
ALTER TABLE cameras ADD COLUMN camera_id_new BIGINT GENERATED BY DEFAULT AS IDENTITY;

-- Update visits table to handle the transition
-- First, let's add a new camera_id_new column to visits as well
ALTER TABLE visits ADD COLUMN camera_id_new BIGINT;

-- Create a mapping table to store old camera_id -> new camera_id_new mappings
CREATE TEMP TABLE camera_id_mapping AS
SELECT 
    tenant_id,
    site_id,
    camera_id as old_camera_id,
    camera_id_new as new_camera_id
FROM cameras
WHERE camera_id_new IS NOT NULL;

-- Update visits table with new camera IDs
UPDATE visits 
SET camera_id_new = cim.new_camera_id
FROM camera_id_mapping cim
WHERE visits.tenant_id = cim.tenant_id 
  AND visits.site_id = cim.site_id 
  AND visits.camera_id = cim.old_camera_id;

-- Drop the old foreign key constraint on visits
ALTER TABLE visits DROP CONSTRAINT IF EXISTS visits_tenant_id_site_id_camera_id_fkey;
ALTER TABLE visits DROP CONSTRAINT IF EXISTS fk_visits_camera;

-- Drop the old camera_id column from visits and rename the new one
ALTER TABLE visits DROP COLUMN camera_id;
ALTER TABLE visits RENAME COLUMN camera_id_new TO camera_id;

-- Now update the cameras table
-- Drop the old primary key constraint
ALTER TABLE cameras DROP CONSTRAINT cameras_pkey;

-- Drop the old camera_id column and rename the new one
ALTER TABLE cameras DROP COLUMN camera_id;
ALTER TABLE cameras RENAME COLUMN camera_id_new TO camera_id;

-- Make the new camera_id NOT NULL
ALTER TABLE cameras ALTER COLUMN camera_id SET NOT NULL;

-- Add the new primary key constraint
ALTER TABLE cameras ADD PRIMARY KEY (tenant_id, site_id, camera_id);

-- Recreate the foreign key constraint on visits
ALTER TABLE visits ADD CONSTRAINT fk_visits_camera 
    FOREIGN KEY (tenant_id, site_id, camera_id) 
    REFERENCES cameras(tenant_id, site_id, camera_id) 
    ON DELETE CASCADE;

-- Add comment to document the change
COMMENT ON COLUMN cameras.camera_id IS 'Auto-incrementing bigint camera identifier for better performance and uniqueness';