"""Add all tables with camera_type column

Revision ID: 5e1ced01ece7
Revises: f5c54a22f4c0
Create Date: 2025-08-20 03:13:29.069166+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e1ced01ece7'
down_revision: Union[str, None] = 'f5c54a22f4c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    op.execute("CREATE TYPE cameratype AS ENUM ('RTSP', 'WEBCAM')")
    op.add_column('cameras', sa.Column('camera_type', sa.Enum('RTSP', 'WEBCAM', name='cameratype'), nullable=False, server_default='RTSP'))
    op.add_column('cameras', sa.Column('device_index', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cameras', 'device_index')
    op.drop_column('cameras', 'camera_type')
    # Drop the enum type
    op.execute("DROP TYPE cameratype")
    # ### end Alembic commands ###
    # ### end Alembic commands ###